export declare class VgAPI {
    medias: Object;
    videogularElement: Object;
    constructor();
    getDefaultMedia(): any;
    getMediaById(id: string): any;
    play(): void;
    pause(): void;
    duration: {};
    state: {};
    volume: {};
    playbackRate: {};
    canPlay: {};
    canPlayThrough: {};
    isMetadataLoaded: {};
    isWaiting: {};
    isCompleted: {};
    time: {};
    buffered: {};
    seekTime(value?: number, byPercent?: boolean): void;
    $$seek(media: HTMLVideoElement | HTMLAudioElement, value?: number, byPercent?: boolean): void;
    $$getAllProperties(property: string): {};
    $$setAllProperties(property: string, value: any): void;
    registerElement(elem: HTMLElement): void;
    registerMedia(media: any): void;
    toggleFullscreen(element: any): void;
    isFullscreen(): boolean;
    connect(media: HTMLElement): void;
    onCanPlay(id: string): void;
    onCanPlayThrough(id: string): void;
    onLoadMetadata(id: string): void;
    onWait(id: string): void;
    onComplete(id: string): void;
    onStartPlaying(id: string): void;
    onPlay(id: string): void;
    onPause(id: string): void;
    onPlaybackChange(id: string, rate: string): void;
    onTimeUpdate(id: string): void;
    onProgress(id: string): void;
    onVolumeChange(id: string): void;
    onError(id: string): void;
}
