import { EventEmitter } from '@angular/core';
import { IPlayable } from "../vg-media/i-playable";
export declare class VgAPI {
    medias: Object;
    videogularElement: any;
    playerReadyEvent: EventEmitter<any>;
    constructor();
    onPlayerReady(): void;
    getDefaultMedia(): IPlayable;
    getMasterMedia(): IPlayable;
    isMasterDefined(): boolean;
    getMediaById(id?: string): IPlayable;
    play(): void;
    pause(): void;
    readonly duration: any;
    currentTime: any;
    state: any;
    volume: any;
    playbackRate: any;
    readonly canPlay: any;
    readonly canPlayThrough: any;
    readonly isMetadataLoaded: any;
    readonly isWaiting: any;
    readonly isCompleted: any;
    readonly time: any;
    readonly buffer: any;
    readonly buffered: any;
    readonly subscriptions: any;
    seekTime(value: number, byPercent?: boolean): void;
    $$seek(media: IPlayable, value: number, byPercent?: boolean): void;
    $$getAllProperties(property: string): any;
    $$setAllProperties(property: string, value: any): void;
    registerElement(elem: HTMLElement): void;
    registerMedia(media: IPlayable): void;
}
