import { ElementRef, OnInit } from '@angular/core';
import { IPlayable } from "./i-playable";
export declare class VgMedia implements OnInit, IPlayable {
    elem: any;
    private _vgMaster;
    isMaster: boolean;
    state: string;
    time: any;
    buffer: any;
    subscriptions: any;
    canPlay: boolean;
    canPlayThrough: boolean;
    isMetadataLoaded: boolean;
    isWaiting: boolean;
    isCompleted: boolean;
    constructor(ref: ElementRef);
    ngOnInit(): void;
    onMutation(mutations: any): void;
    play(): void;
    pause(): void;
    readonly id: any;
    readonly duration: any;
    currentTime: any;
    volume: any;
    playbackRate: any;
    readonly buffered: any;
    onCanPlay(event: any): void;
    onCanPlayThrough(event: any): void;
    onLoadMetadata(event: any): void;
    onWait(event: any): void;
    onComplete(event: any): void;
    onStartPlaying(event: any): void;
    onPlay(event: any): void;
    onPause(event: any): void;
    onTimeUpdate(event: any): void;
    onProgress(event: any): void;
    onVolumeChange(event: any): void;
    onError(event: any): void;
}
