import { ElementRef, OnInit } from '@angular/core';
import { IPlayable } from "../vg-media/i-playable";
import { SlideModel } from "./slide-model";
export declare class VgSlides implements OnInit, IPlayable {
    slides: Array<SlideModel>;
    elem: IPlayable;
    state: string;
    time: any;
    buffer: any;
    subscriptions: any;
    canPlay: boolean;
    canPlayThrough: boolean;
    isMetadataLoaded: boolean;
    isWaiting: boolean;
    isCompleted: boolean;
    id: string;
    duration: number;
    currentTime: number;
    volume: number;
    playbackRate: number;
    buffered: TimeRanges;
    currentSlide: SlideModel;
    progress: any;
    lastTime: number;
    constructor(ref: ElementRef);
    ngOnInit(): void;
    onSeek(): void;
    expose(): void;
    play(): void;
    pause(): void;
    changeToSlide(slide: SlideModel): void;
    onProgress(currentTime: any): void;
    onComplete(): void;
}
